if(NOT Boost_FOUND)
  if(POLICY CMP0167)
    if(Boost_DIR AND EXISTS "${Boost_DIR}/BoostConfig.cmake")
      cmake_policy(SET CMP0167 NEW)
    else()
      cmake_policy(SET CMP0167 OLD)
    endif()
  endif()
  if(MITK_USE_Boost_LIBRARIES)
    find_package(Boost 1.60.0 REQUIRED COMPONENTS ${MITK_USE_Boost_LIBRARIES} QUIET)
  else()
    find_package(Boost 1.60.0 REQUIRED QUIET)
  endif()
endif()

if(TARGET Boost::headers)
  get_target_property(_crimson_boost_inc Boost::headers INTERFACE_INCLUDE_DIRECTORIES)
  if(_crimson_boost_inc)
    list(APPEND ALL_INCLUDE_DIRECTORIES ${_crimson_boost_inc})
  endif()
elseif(Boost_INCLUDE_DIRS)
  list(APPEND ALL_INCLUDE_DIRECTORIES ${Boost_INCLUDE_DIRS})
endif()

if(Boost_LIBRARIES)
  if(WIN32)
    # Force dynamic linking
    list(APPEND ALL_COMPILE_OPTIONS -DBOOST_ALL_DYN_LINK)
  else()
    # Boost has an auto link feature (pragma comment lib) for Windows
    list(APPEND ALL_LIBRARIES ${Boost_LIBRARIES})
  endif()
endif()
