# Honor explicit install dir (seeded by SuperBuild initial cache) and MITK superbuild layout.
if(NOT CGAL_DIR AND DEFINED ENV{CGAL_DIR})
  set(CGAL_DIR "$ENV{CGAL_DIR}")
endif()
find_package(CGAL REQUIRED)

if(TARGET CGAL::CGAL)
  list(APPEND ALL_LIBRARIES CGAL::CGAL)
else()
  include(${CGAL_USE_FILE})
  if(DEFINED CGAL_INCLUDE_DIR)
    list(APPEND ALL_INCLUDE_DIRECTORIES ${CGAL_INCLUDE_DIR})
  endif()
  if(DEFINED CGAL_LIBRARY AND CGAL_LIBRARY)
    list(APPEND ALL_LIBRARIES ${CGAL_LIBRARY})
  endif()
endif()
