# CONFIG: CGAL_DIR is set by SuperBuild / CrimsonPreparePrebuiltMITK (vcpkg).
find_package(CGAL CONFIG REQUIRED)

if(TARGET CGAL::CGAL)
  list(APPEND ALL_LIBRARIES CGAL::CGAL)
else()
  include(${CGAL_USE_FILE})
  if(DEFINED CGAL_INCLUDE_DIR)
    list(APPEND ALL_INCLUDE_DIRECTORIES ${CGAL_INCLUDE_DIR})
  endif()
  if(DEFINED CGAL_LIBRARY AND CGAL_LIBRARY)
    list(APPEND ALL_LIBRARIES ${CGAL_LIBRARY})
  endif()
endif()
